config/routes.rb
require 'sidekiq/web'

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
#
Rails.application.routes.draw do

  resources :users, only: [:show, :index] do
    collection do
      get :csv_import_modal
      post :import_from_csv
    end
  end

  devise_for :users
  get '/pandas', to: 'pandas#index'

  root to: 'home#index'
end

app/models/animal.rb
class Animal < ApplicationRecord
  validates :name, presence: true
  validates :age_years, presence: true, numericality: { greater_than: 0 }
  validates :type, presence: true

  self.inheritance_column = :_type_disabled
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/animals/pandas_controller.rb
module Animals
  class PandasController < ApplicationController
    def index
      @data = {
        pandas: Animal.where(type: 'Panda').order(:name)
      }
    end
  end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: %i[ show edit update destroy ]

  # GET /animals or /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1 or /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals or /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to animal_url(@animal), notice: "Animal was successfully created." }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1 or /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to animal_url(@animal), notice: "Animal was successfully updated." }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1 or /animals/1.json
  def destroy
    @animal.destroy

    respond_to do |format|
      format.html { redirect_to animals_url, notice: "Animal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animal_params
      params.require(:animal).permit(:name, :age_years, :type)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    # if Rails.cache.read('users/import_progress') != "in_progress"
    #   ImportContactsJob.perform_later
    # end

    # Rails.cache.write('users/import_progress', "in_progress")
    #
    @data = {
      users: User.all
    }
  end

  def csv_import_modal; end

  def import_from_csv
    @import_result = ::Users::CsvUploadParser.new(params[:users_csv].read).import_users_from_csv
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def add_vue_props(data)
    return unless data

    "data-props=#{data.to_json}"
  end
end

app/helpers/pandas_helper.rb
module PandasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animals/_animal_table_row.html.erb
<tr id="<%= dom_id animal %>">
  <td class="px-6 py-4 text-center"><%= animal.name %></td>
  <td class="px-6 py-4 text-center"><%= animal.age_years %></td>
  <td class="px-6 py-4 text-center"><%= animal.type %></td>
  <td class="px-6 py-4 text-right">
    <%= link_to "Details", animal, class: "mt-4 text-purple-400 hover:text-purple-200" %>
  </td>
</tr>

app/views/animals/_form.html.erb
<%= form_with(model: animal, class: "w-full max-w-sm") do |form| %>
  <% if animal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
        <% animal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
      <%= form.label :name, class: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
    </div>
    <div class="md:w-2/3">
      <%= form.text_field :name, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
    </div>
  </div>
  <div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
      <%= form.label :age_years, class: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
    </div>
    <div class="md:w-2/3">
      <%= form.number_field :age_years, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
    </div>
  </div>
  <div class="md:flex md:items-center mb-6">
    <div class="md:w-1/3">
      <%= form.label :type, class: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" %>
    </div>
    <div class="md:w-2/3">
      <%= form.text_field :type, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
    </div>
  </div>
  <div class="md:flex md:items-center">
    <div class="md:w-1/3"></div>
    <div class="md:w-2/3">
      <%= form.submit class: "shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded cursor-pointer" %>
    </div>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing animal</h1>

<%= render "form", animal: @animal %>

<br>

<div>
  <%= link_to "Show this animal", @animal %> |
  <%= link_to "Back to animals", animals_path %>
</div>

app/views/animals/index.html.erb
<div class="max-w-screen-lg mx-auto mt-16">
  <h1 class="text-2xl mb-3">Animals</h1>

  <%= link_to "New animal", new_animal_path, class: "mt-4 text-purple-400 hover:text-purple-200" %>

  <table id="animals" class="relative w-full border mt-4">
    <thead>
      <tr>
        <th class="sticky top-0 px-6 py-3 text-purple-900 bg-purple-300">Name</th>
        <th class="sticky top-0 px-6 py-3 text-purple-900 bg-purple-300">Age</th>
        <th class="sticky top-0 px-6 py-3 text-purple-900 bg-purple-300">Type</th>
        <th class="sticky top-0 px-6 py-3 text-purple-900 bg-purple-300">Actions</th>
      </tr>
    </thead>
    <tbody class="divide-y bg-purple-100 dark:bg-purple-700">
      <% @animals.each do |animal| %>
        <%= render partial: "animal_table_row", locals: { animal: animal } %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/animals/new.html.erb
<div class="max-w-screen-lg mx-auto mt-16">
  <h1 class="text-2xl mb-3" >New animal</h1>

  <%= render "form", animal: @animal %>

  <%= link_to "Back to animals", animals_path, class: "mt-4 text-purple-400 hover:text-purple-200" %>
</div>

app/views/animals/pandas/index.html.erb
<%= content_for :page_title do %>
  Pandas
<% end %>

<div class="max-w-screen-lg mx-auto mt-16">
  <div id="pandas-view" <%= add_vue_props(@data) %>></div>
</div>

app/views/animals/show.html.erb
<div class="max-w-screen-lg mx-auto mt-16">
  <%= render @animal %>

  <div>
    <%= link_to "Edit this animal", edit_animal_path(@animal) %> |
    <%= link_to "Back to animals", animals_path %>

    <%= button_to "Delete", @animal, method: :delete, class: "shadow bg-red-500 hover:bg-red-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded cursor-pointer" %>
  </div>
</div>

app/views/home/index.html.erb
<div class="max-w-screen-sm mx-auto">
  <div id="root-view">
    <template>
      <div v-cloak>
        {{ count }}
        {{ countDouble }}
        <button @click="onClick">Increase Count</button>
      </div>
    </template>

    <script setup>
      function options() {
        return {
          data: () => {
            return {
              count: 0,
            };
          },
          methods: {
            onClick() {
              this.count++;
            },
          },
          computed: {
            countDouble() {
              return this.count * 2;
            },
          }
        };
      }
    </script>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="antialiased bg:white dark:bg-slate-800" lang="en">
  <%= render "shared/head" %>

  <body class="font-sans font-normal leading-normal text-slate-800 dark:text-gray-50">
    <%= render "shared/header" %>

    <turbo-frame id="modal"> </turbo-frame>

    <main class="px-4 lg:px-10 mt-10 max-w-screen-lg mx-auto">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/pandas/index.html.erb
<%= content_for :page_title do %>
  Pandas
<% end %>

<div id="pandas-view" <%= add_vue_props(@data) %>></div>

<h2 class="text-xl mb-5">
  <a href="https://www.pandaipsum.com/" target="_blank">Pandas Ipsum</a>
</h2>

<p class="mb-3">
  Panda Ipsum the Red panda dances. To ailuridae. Ago. Pandas why the only
  ovulate once each year. During that ovulation period, they are two main
  types of the ipsum all about pandas. The panda loves being cool ipsum with
  giant panda bear giant panda loves leaves to dance and the ipsum all about
  pandas. The red panda dances. The red panda and the forest as the genus
  Ailurus and eat bamboo in the earth as three million years ago. There are
  only ovulate once each year. During that ovulation period, they are only
  fertile for two main types of the Red Panda. Female pandas only living
  species of the population has dwindled. The red panda loves leaves to
  dance and the Red Panda. Female pandas roamed.
</p>
<p class="mb-3">
  Red panda red panda is the earth as three million years ago. There are
  only fertile for two or three million years ago. There are only ovulate
  once each year. During that pandas roamed the only ovulate once each year.
  During that pandas roamed the forest as three days. That is believed that
  pandas roamed the forest. Panda Ipsum the forest. Panda Ipsum the cool
  ipsum all about pandas. The red panda eat bamboo leaves. Red panda bear
  giant panda and the only living species of pandas, the giant panda cute
  panda. Panda Ipsum the cool ipsum eating bamboo in the.
</p>
<p class="mb-3">
  Cool tiny panda bear giant panda and eat bamboo in the genus Ailurus and
  the reasons why the red panda is the red panda dancing panda. Panda Ipsum
  the forest. Panda Ipsum the Red Panda. Female pandas only fertile for two
  or three million years ago. There are only living species.
</p>
<p class="mb-3">
  Bamboo leaves. Red Panda. Female pandas roamed the forest. Cute panda red
  panda bear. Giant panda is believed that ovulation period, they are only
  ovulate once each year. During that pandas only fertile for two or three
  million years ago. There are two main types of the forest. Panda Ipsum the
  forest. Panda Ipsum panda likes great panda bear. It is the forest. Cute
  panda cute tiny dancing panda. Panda Ipsum the red panda relaxing in the
  family Ailuridae. Panda, panda, panda, panda, panda loves leaves to dance
  and the earth as the family Ailuridae. Panda, panda, panda cute panda.
  Board.
</p>
<p class="mb-3">
  Being cool tiny panda eat bamboo leaves. Red panda loves being cool ipsum
  all about pandas. The panda loves being cool ipsum eating bamboo in the
  Red panda cute panda. Board panda loves leaves to dance and the forest.
  Cute panda eat bamboo in the ipsum with giant black-and-white panda ipsum
  eating bamboo in the population has dwindled. The panda bear. Giant panda
  cute panda. Panda Ipsum the genus Ailurus and eat bamboo in the red panda
  dances. Early in the ipsum with giant panda bear giant black-and-white
  panda loves being cool ipsum eating bamboo in the cool ipsum eating bamboo
  in the ipsum eating bamboo in the forest as three million years ago. There
  are only fertile for two main types of the cool tiny.
</p>
<p class="mb-3">
  Being cool ipsum eating bamboo in the family Ailuridae. Panda, panda,
  panda, panda, panda, panda, panda dancing panda. Board panda dances.
  Million roamed the forest as early as early as three days. That is cute
  tiny dancing bear. Giant panda relaxing in the ipsum eating bamboo in the
  Red Panda. Female.
</p>
<p class="mb-3">
  Ipsum the forest. Cute panda relaxing in the forest. Cute panda loves
  leaves to dance and eat bamboo in the ipsum eating bamboo in the family
  Ailuridae. Panda, panda, panda, panda, panda is cute panda. Board panda
  ipsum all about pandas. The panda is one of the population has dwindled.
  The panda bear. It is believed that ovulation period, they are only
  fertile for two main types of the red panda cute panda. Board panda eat.
</p>
<p class="mb-3">
  That pandas only fertile for two main types of the reasons why the ipsum
  with giant black-and-white panda and the earth as early as early as three
  million years ago. There are only fertile for two or three million years
  ago. There are two main types of the population has dwindled. The red
  panda is believed that pandas only ovulate once each year. During that
  pandas only ovulate once each year. During that pandas only fertile.
</p>
<p class="mb-3">
  Panda, panda, panda, panda ipsum with giant black-and-white panda dances.
  All it female giant black-and-white panda likes great panda ipsum with
  giant panda bear giant panda bear. Giant panda red panda eat bamboo in the
  population has dwindled. The panda red panda is cute tiny panda eat bamboo
  leaves. Red Panda.
</p>
<p class="mb-3">
  Great panda is one of the reasons why the reasons why the forest. Panda
  Ipsum the forest as three days. That is believed that ovulation period,
  they are two main types of the forest as the genus Ailurus and the only
  fertile for two or three days. That is cute panda.
</p>

<div id="lazy-load"></div>

app/views/shared/_github_icon_link.html.erb
<a href="https://github.com/joekrump/rails-turbo-vue.git" target="_blank">
  <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 496 512" class="fill-black hover:fill-purple-600 dark:fill-white dark:hover:fill-purple-300"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"/></svg>
</a>

app/views/shared/_head.html.erb
 <head>
  <title>
    <% if content_for?(:page_title) %>
      <%= yield :page_title %> |
    <% end %>
    Rails + Vue ⚡️
  </title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= vite_client_tag %>
  <%= vite_stylesheet_tag 'application.css' %>
  <%= vite_typescript_tag 'application' %>
  <%= vite_typescript_tag 'turbo-vue' %>
    <!--
      If using a TypeScript entrypoint file:
        vite_typescript_tag 'application'

      Visit the guide for more information: https://vite-ruby.netlify.app/guide/rails
    -->
</head>

app/views/shared/_header.html.erb
<header class="sticky top-0">
  <nav class="flex flex-wrap items-center justify-between px-3 py-3 bg-gray-100 lg:px-10 dark:bg-slate-900">
    <%= link_to "Rails + Vue", root_path, class: "text-2xl font-bold text-gray-900 dark:text-green-600 dark:hover:text-green-200" %>

    <div class="flex gap-3 items-center">
      <%= link_to "Pandas", pandas_path, class: "text-xl font-bold text-purple-600 dark:text-purple-400 hover:text-purple-800 dark:hover:text-purple-200" %>
      <%= render "shared/github_icon_link" %>
    </div>
  </nav>
</header>

app/views/users/_progress_bar.html.erb
<section id="users_progress_bar">
  <div class="w-full bg-neutral-200 dark:bg-neutral-600 relative overflow-hidden rounded">
    <div class="w-full text-center text-xs py-1 font-bold text-white leading-none absolute top-0">
      <%= "#{processed_count}/#{total}" %> rows processed
    </div>
    <div
      class="bg-purple-500 h-5"
      style="width: <%= percentage_complete %>%"
      role="progressbar" aria-valuenow="<%= processed_count %>" aria-valuemin="0" aria-valuemax="<%= total %>"
    >
    </div>
  </div>
</section>

app/views/users/csv_import_modal.html.erb
<%= turbo_frame_tag "modal" do %>
  <dialog class="w-full max-w-3xl bg-white dark:bg-slate-900 rounded-md shadow p-0 dark:text-gray-200">
    <header class="px-5 py-4 border border-t-0 border-x-0 border-gray-400 dark:border-gray-800 sticky top-0">
      <h1 class="text-lg leading-8 font-medium">Import Users</h1>
    </header>
    <%= form_with url: import_from_csv_users_path, multipart: true, method: "post" do |form| %>
      <section class="px-5 py-10 mt-5 grid place-content-center">
        <turbo-frame id="users_import_notice"></turbo-frame>
        <div class="text-center">
          <p class="my-2">Upload a CSV here to import users</p>
          <%= file_field_tag :users_csv, accept: ".csv", class: "text-purple-500 hover:text-purple-600" %>
        </div>
        <%= turbo_stream_from 'users' %>
        <div id="users_progress_bar"></div>
        <turbo-frame id="users_import_errors"></turbo-frame>
      </section>
      <footer class="px-5 py-4 flex justify-between border border-gray-400 dark:border-gray-800 border-b-0 border-x-0 sticky bottom-0 ">
        <button
          autofocus
          type="reset"
          class="bg-white hover:bg-gray-50 text-gray-800 dark:bg-slate-700 dark:hover:bg-slate-600 dark:text-white font-medium py-1.5 px-3 border border-gray-300 dark:border-slate-800 shadow rounded"
          onclick="this.closest('dialog').close('close')"
        >
          Cancel
        </button>
        <button type="submit" class=" bg-purple-500 hover:bg-purple-600 text-white py-1.5 px-3 font-medium whitespace-nowrap rounded">
          Import Users
        </button>
      </footer>
    <% end %>
  </dialog>
<% end %>

app/views/users/import_from_csv.turbo_stream.erb
<% if @import_result[:successfully_imported_count] > 0 %>
  <turbo-stream action="update" target="users_import_notice">
    <template>
      <div class="bg-green-100 border border-green-400 text-green-700 border-l-4 mb-4 p-4" role="alert">
        <h1 class="font-bold">Successfully imported <%= pluralize(@import_result[:successfully_imported_count], "user") %></h1>
      </div>
    </template>
  </turbo-stream>
<% end %>

<% if @import_result[:errors] %>
  <turbo-stream action="update" target="users_import_errors">
    <template>
      <div class="bg-red-100 border border-red-400 text-red-700 border-l-4 mt-4 p-4" role="alert">
        <h1 class="font-bold">Failed to import <%= pluralize(@import_result[:errors].size, "user") %></h1>
        <ul>
        <% @import_result[:errors].each do |row, error_message| %>
          <li><%= row %>: <%= error_message %></li>
        <% end %>
        </ul>
      </div>
    </template>
  </turbo-stream>
<% end %>

app/views/users/index.html.erb
<div class="max-w-screen-lg mx-auto mt-16">
  <div id="vue-root" <%= add_vue_props(@data) %>></div>
</div>

app/views/users/show.html.erb
<div>
  <h1 class="font-bold text-4xl"><%= @user.email %></h1>
</div>